### ISSUE TITLE
Image processing - image segmentation

### ISSUE THREAD

**Issue by eladbd** [Ido-Cohen/TheUnseenView#6]

**Comment by Ido-Cohen** [comment]
this component is finished, we had to change a few things in the Detectron2 library in order to remove the text labels from the processed image, the library do not have a built-in option to remove it when using panoptic segmentation.

**Comment by Ido-Cohen** [comment]
![4_out](https://user-images.githubusercontent.com/61789416/236201534-996cc575-6ec2-4adc-9ddc-f4e4b446d14a.jpg)
